### ISSUE TITLE
not show last month days in this month 

### ISSUE THREAD

**Issue by andyliuAccenture** [Adphorus/react-date-range#124]
how can I config to not show the last month in current month when I rendering two month at once 
thank u very much

**Comment by missmatsuko** [comment]
I'd also like the next month's date to be selectable when shown.

**Comment by mimshwright** [comment]
@missmatsuko You should probably make that a separate issue so this one can be closed.

**Comment by missmatsuko** [comment]
@mimshwright ok I made issue #144

**Comment by mac-s-g** [comment]
currently doing this with css selectors because the default style causes dates to look disabled:
```css
& .rdrDayPassive > .rdrDayNumber * {
  color: transparent !important;
}
```
