### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by andyliuhaowen** [Adphorus/react-date-range#288]
I would like to use DateRangePicker for large screens and up and DateRange otherwise.

I tried to use react-socks breakpoints to do that but react will render whatever that comes first regardless of screen size.

Probably this is not the right way to do it. Does anybody have a better way to make that happen? Or, even better, can this responsiveness be natively supported by react-date-range through its options?

Package Version:
React version: 16.8.1
Node version: 10.15.3
React-socks version: 1.0.1
Browser: Firefox and Chrome

**Comment by JohnWelle** [comment]
Not a perfect solution, but if you add a custom class for the wrapper element, you can set `flex-direction: column` to make the quick picker render above the calendar with a media query, eg something like:

Similarly, you could also override the theme style to set the quick picker to `display: none`

```scss
.picker {
  // other overrides
  @media (min-width: 320px) and (max-width: 480px) {
    display: flex;
    flex-direction: column;
  }
}
```

![image](https://user-images.githubusercontent.com/5860390/56279397-4bbfbb80-6108-11e9-944e-012fb586356a.png)
