### ISSUE TITLE
All the dates are selected in date range picker when setting startDate and endDate null or empty

### ISSUE THREAD

**Issue by manishg345** [Adphorus/react-date-range#360]
## Subject of the issue
All the dates are selected in date range picker when setting startDate and endDate null or empty
 
## [BUG] Bug Reproduce Steps
In DateRangePicker state object, set startDate and endDate as null

## [BUG] Expected behaviour
Initially when both of the date textfields are set as blank, none of the date should be selected in the calendar of DRP 

## Environment
Package Version:
React version:
Node version:
Browser:

**Comment by shaohuahuang** [comment]
+1

**Comment by ao-alex** [comment]
+1

**Comment by fsdiogo** [comment]
+1, every day gets the `rdrInRange` class, which just doesn't make sense.

**Comment by gaieges** [comment]
Noted the same / similar issue in https://github.com/hypeserver/react-date-range/issues/330#issuecomment-721482829 with some demos there.

**Comment by bertho-zero** [comment]
To work around this I added a class `rdrNoSelection`:

```js
  const rdrNoSelection = useMemo(
    () => {
      const range = ranges?.[0];
      return !range || (range.startDate === null && range.endDate === null);
    },
    [ranges]
  );
```

```scss
.rdrNoSelection {
  .rdrSelected, .rdrInRange, .rdrStartEdge, .rdrEndEdge {
    background: #fff;
  }

  .rdrDay:not(.rdrDayPassive) .rdrInRange ~ .rdrDayNumber span,
  .rdrDay:not(.rdrDayPassive) .rdrStartEdge ~ .rdrDayNumber span,
  .rdrDay:not(.rdrDayPassive) .rdrEndEdge ~ .rdrDayNumber span,
  .rdrDay:not(.rdrDayPassive) .rdrSelected ~ .rdrDayNumber span {
    color: $oa-black;

    &:after {
      background: $oa-blue;
    }
  }
}
```
